package pl.pateman.forwardplus.pipeline.step;

import org.joml.Matrix3f;
import org.joml.Matrix4f;
import org.joml.Vector3f;
import org.joml.Vector4f;
import pl.pateman.forwardplus.scene.Scene;
import pl.pateman.forwardplus.scene.entity.mesh.MeshInstance;
import pl.pateman.forwardplus.shader.ShaderProgram;
import pl.pateman.forwardplus.util.TempVars;

import static org.lwjgl.opengl.GL11C.*;
import static org.lwjgl.opengl.GL13C.GL_TEXTURE1;
import static org.lwjgl.opengl.GL13C.glActiveTexture;
import static org.lwjgl.opengl.GL30C.*;
import static org.lwjgl.opengl.GL43C.GL_SHADER_STORAGE_BUFFER;

public class ForwardPassStep extends AbstractPipelineStep {

    private final int mainFbo;
    private final ShaderProgram forwardProgram;

    public ForwardPassStep(int mainFbo, ShaderProgram forwardProgram) {
        this.mainFbo = mainFbo;
        this.forwardProgram = forwardProgram;
    }

    @Override
    public void init() {
        // Do nothing.
    }

    @Override
    public void render(Scene scene) {
        Integer screenWidth = getInput("screenWidth", Integer.class);
        Integer screenHeight = getInput("screenHeight", Integer.class);
        Matrix4f viewMatrix = getInput("viewMatrix", Matrix4f.class);
        Vector3f sunDirection = getInput("sunDirection", Vector3f.class);

        glBindFramebuffer(GL_FRAMEBUFFER, mainFbo);
        glViewport(0, 0, screenWidth, screenHeight);

        glEnable(GL_DEPTH_TEST);

        // Use the depth generated by the pre-pass.
        // Because both vertex shaders declare invariant gl_Position,
        // GL_EQUAL should now be stable and avoids "stitching" artifacts.
        glDepthFunc(GL_EQUAL);
        glDepthMask(false);

        glClearColor(0.015f, 0.018f, 0.025f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);

        forwardProgram.use();

        forwardProgram.setMat4("uView", viewMatrix);
        forwardProgram.setMat4("uProjection", getInput("projectionMatrix", Matrix4f.class));
        forwardProgram.setInt("uScreenSizeX", screenWidth);
        forwardProgram.setInt("uScreenSizeY", screenHeight);
        forwardProgram.setInt("uTileCountX", getInput("tilesX", Integer.class));
        forwardProgram.setInt("uTileCountY", getInput("tilesY", Integer.class));
        forwardProgram.setInt("uDebugTiles", getInput("isDebug", Boolean.class) ? 1 : 0);
        forwardProgram.setMat4("uLightSpaceMatrix", getInput("lightSpaceMatrix", Matrix4f.class));

        TempVars tempVars = TempVars.get();

        Vector4f sunDirView4 = tempVars.vect4d1.set(
                sunDirection.x,
                sunDirection.y,
                sunDirection.z, 0.0f);
        viewMatrix.transform(sunDirView4);
        Vector3f sunDirView = tempVars.vect3d1.set(sunDirView4.x, sunDirView4.y, sunDirView4.z).normalize();
        forwardProgram.setVec3("uSunDirectionView", sunDirView);
        forwardProgram.setVec3("uSunColor", tempVars.vect3d2.set(1.0f, 0.94f, 0.82f));

        glActiveTexture(GL_TEXTURE1);
        glBindTexture(GL_TEXTURE_2D, getInput("shadowDepthTexture", Integer.class));
        forwardProgram.setInt("uShadowMap", 1);

        glBindBufferBase(GL_SHADER_STORAGE_BUFFER, 0, getInput("lightSsbo", Integer.class));
        glBindBufferBase(GL_SHADER_STORAGE_BUFFER, 1, getInput("tileHeaderSsbo", Integer.class));
        glBindBufferBase(GL_SHADER_STORAGE_BUFFER, 2, getInput("lightIndexSsbo", Integer.class));

        for (int i = 0; i < scene.getMeshInstances().size(); i++) {
            MeshInstance instance = scene.getMeshInstances().get(i);
            Matrix4f modelView = tempVars.tempMat4x41.set(viewMatrix).mul(instance.model());
            Matrix3f normalMatrix = tempVars.tempMat3x3.set(modelView).invert().transpose();

            forwardProgram.setMat4("uModel", instance.model());
            forwardProgram.setMat3("uNormalMatrix", normalMatrix);
            forwardProgram.setVec3("uAlbedo", instance.albedo());

            instance.mesh().draw();
        }

        glDepthMask(true);
        glDepthFunc(GL_LESS);

        tempVars.release();
    }

    @Override
    public void destroy() {
        // Do nothing.
    }
}
